### ISSUE TITLE
How to can i use my own skins on this client?

### ISSUE THREAD

**Issue by josefredohd** [NuclearC/NuclearC.github.io#2]

**Comment by NuclearC** [comment]
you need to define your own MC.getSkinInfo function, which takes one argument <skinname> and returns object like {url: <skinURL>, color: <cellColor>}

**Comment by josefredohd** [comment]
I do not know much about JavaScript, could you help me please?

**Comment by josefredohd** [comment]
@NuclearC Help me pls

**Comment by josefredohd** [comment]
function hc(a) {
                if (null == a || 0 == a.length) return null;
                if (!oa.hasOwnProperty(a)) {
                    var b = new Image;
                    if (":" == a[0]) b.src = a.slice(1);
                    else if ("%" == a[0]) {
                        if (!c.MC || !c.MC.getSkinInfo) return null;
                        var d = c.MC.getSkinInfo("skin_" + a.slice(1));
                        if (null == d) return null;
                        b.src = c.ASSETS_ROOT + d.url
                    }

This function?
